"""Markdown + JSON reports for an autonomous audit."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from self_tool.autonomous.models import AutonomousAudit
from self_tool.core.issue import Severity


def write_reports(audit: AutonomousAudit, markdown_path: str, also_json: bool = False) -> str:
    md = render_markdown(audit)
    path = Path(markdown_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(md, encoding="utf-8")
    if also_json:
        json_path = path.with_suffix(".json") if path.suffix.lower() == ".md" else Path(str(path) + ".json")
        json_path.write_text(json.dumps(audit.to_dict(), indent=2, sort_keys=True), encoding="utf-8")
    return md


def render_markdown(audit: AutonomousAudit) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    u = audit.understanding
    counts = _counts([item.severity for item in audit.findings] + [
        issue.severity for issue in audit.static_issues if not issue.suppressed
    ])
    lines = [
        "# SELF Autonomous Audit",
        "",
        f"> Generated by SELF v{audit.version} on {now}.",
        "> This is an autonomous first-pass: static detectors + trained playbooks "
        "+ project understanding + dependency advisories"
        + (" + an optional LLM pass." if audit.llm_used else "."),
        "> It does **not** replace a manual audit.",
        "",
        "## Protocol understanding",
        "",
        f"- **Name:** {u.name}",
        f"- **Types:** {', '.join(u.types) or 'unknown'}",
        f"- **Languages:** {', '.join(u.languages) or 'unknown'}",
        f"- **Files / source chars:** {u.file_count} / {u.source_chars}",
        f"- **Project fingerprint:** `{audit.project_fingerprint}`",
        f"- **Summary:** {u.summary}",
        "",
        "### Contest / documentation brief",
        "",
    ]
    if u.trusted_roles:
        lines.append("- **Trusted roles:** " + ", ".join(f"`{_cell(role)}`" for role in u.trusted_roles[:16]))
    if u.known_issues:
        lines.append(f"- **Known issues kept in mind:** {len(u.known_issues)}")
        lines.extend(f"  - {_cell(item)}" for item in u.known_issues[:10])
    if u.accepted_playbooks:
        lines.append("- **Accepted risk classes (not re-reported):** " + ", ".join(f"`{item}`" for item in u.accepted_playbooks))
    if u.out_of_scope_paths:
        lines.append(f"- **Out of scope paths:** {len(u.out_of_scope_paths)}")
    if u.in_scope_paths:
        lines.append(f"- **In-scope paths listed:** {len(u.in_scope_paths)}")
    if u.local_audit_files:
        lines.append("- **Local prior-audit / security files:** " + ", ".join(f"`{_cell(item)}`" for item in u.local_audit_files[:10]))
    if u.referenced_urls:
        lines.append(f"- **Documented https links (acknowledged):** {len(u.referenced_urls)}")
        lines.extend(f"  - {_cell(url)}" for url in u.referenced_urls[:12])
    fetched = list(u.fetched_refs or [])
    if fetched:
        ok = sum(1 for item in fetched if item.get("ok"))
        lines.append(f"- **Fetched with `--online`:** {ok}/{len(fetched)}")
        for item in fetched[:8]:
            mark = "ok" if item.get("ok") else "failed"
            lines.append(f"  - [{mark}] {_cell(item.get('url', ''))} ({_cell(item.get('status', ''))})")
    if not (u.trusted_roles or u.known_issues or u.out_of_scope_paths or u.local_audit_files or u.referenced_urls):
        lines.append("- No contest brief (known issues / trusted roles / out-of-scope) was parsed. Re-run without `--no-docs` from the repo root if a README exists.")
    lines.extend([
        "",
        "### Architecture notes",
        "",
    ])
    lines.extend(f"- {_cell(note)}" for note in u.architecture_notes or ["- none"])
    lines.extend(["", "### Active risk facts", ""])
    active = [key for key, value in sorted(u.facts.items()) if value]
    if active:
        lines.extend(f"- `{name}`" for name in active)
    else:
        lines.append("- none fired")
    lines.extend(["", "### Contracts / programs", "",
                  "| Language | Role | Name | File | Fns | Inherits |",
                  "|---|---|---|---|---:|---|"])
    if u.contracts:
        for contract in u.contracts:
            lines.append(
                f"| {contract.language} | {contract.role_guess} | `{contract.name}` | "
                f"`{contract.file}` | {len(contract.functions)} | "
                f"{_cell(', '.join(contract.inherits) or '-')} |"
            )
    else:
        lines.append("| - | - | - | - | 0 | - |")

    lines.extend(["", "### Token flows", ""])
    if u.token_flows:
        for flow in u.token_flows[:30]:
            lines.append(
                f"- `{flow.direction}` `{flow.function}` @ `{flow.file}:{flow.line}` ({_cell(flow.detail)})"
            )
    else:
        lines.append("- none resolved")

    if u.math_formulas:
        lines.extend(["", "### Math models matched", ""])
        lines.extend(f"- {item}" for item in u.math_formulas)

    if u.invariants:
        lines.extend(["", "### Extracted guards (candidates, not proofs)", ""])
        lines.extend(f"- `{_cell(item)}`" for item in u.invariants[:25])

    lines.extend([
        "",
        "## Findings summary",
        "",
        "| Severity | Autonomous | Static |",
        "|---|---:|---:|",
    ])
    auto_counts = _counts(item.severity for item in audit.findings)
    static_counts = _counts(issue.severity for issue in audit.static_issues if not issue.suppressed)
    for sev in Severity.ORDER:
        lines.append(f"| {sev} | {auto_counts.get(sev, 0)} | {static_counts.get(sev, 0)} |")

    lines.extend(["", "## Autonomous findings", ""])
    if audit.findings:
        for item in audit.findings:
            lines.extend(_finding_block(item))
    else:
        lines.append("_No autonomous playbook fired. Static findings may still exist._")

    lines.extend(["", "## Exploit paths", ""])
    if audit.exploit_paths:
        for path in audit.exploit_paths:
            lines.extend([
                f"### {path.severity}: {path.title}",
                "",
                path.narrative,
                "",
            ])
            lines.extend(f"{index}. {_cell(step)}" for index, step in enumerate(path.steps, 1))
            if path.entry_points:
                lines.extend(["", "Entry points:"] + [f"- `{_cell(ep)}`" for ep in path.entry_points])
            if path.related_finding_ids:
                lines.append("Related: " + ", ".join(f"`{i}`" for i in path.related_finding_ids))
            lines.append("")
    else:
        lines.append("_No multi-hop path was synthesized._")

    lines.extend(["", "## Dependency advisories", ""])
    if audit.dependencies:
        lines.extend([
            "| Package | Version | Severity | Advisory | Source |",
            "|---|---|---|---|---|",
        ])
        for hit in audit.dependencies:
            lines.append(
                f"| `{_cell(hit.package)}` | `{_cell(hit.version)}` | {hit.severity} | "
                f"{_cell(hit.title)} | `{_cell(hit.source_file)}` |"
            )
    else:
        lines.append("_No known-vulnerable dependency versions matched the local advisory brain._")

    lines.extend(["", "## Static detector corroboration", ""])
    active_static = [i for i in audit.static_issues if not i.suppressed]
    if active_static:
        lines.extend([
            "| ID | Severity | Title | Location |",
            "|---|---|---|---|",
        ])
        for issue in active_static[:40]:
            lines.append(
                f"| `{issue.id}` | {issue.severity} | {_cell(issue.title)} | "
                f"`{issue.file}:{issue.line}` |"
            )
        if len(active_static) > 40:
            lines.append(f"| … | | {len(active_static) - 40} more | |")
    else:
        lines.append("_No active static findings._")

    trained = audit.trained_on
    lines.extend([
        "",
        "## Training / knowledge",
        "",
        f"- Documents in index: **{trained.get('documents', 0)}**",
        f"- Attack vectors: **{trained.get('attack_vectors', 0)}**",
        f"- Recent incidents (retrieval): **{trained.get('incidents', 0)}**",
        f"- Expert tactics: **{trained.get('expert_tactics', 0)}**",
        f"- Real exploits in corpus: **{trained.get('exploits', 0)}**",
        f"- Languages in brain: **{trained.get('languages', 0)}**",
        f"- Dependency advisories: **{trained.get('dependency_advisories', 0)}**",
        f"- Index built at: {trained.get('built_at') or 'bundled (untrained session used live brain)'}",
        f"- LLM used: {'yes' if audit.llm_used else 'no'}",
    ])
    if audit.llm_error:
        lines.append(f"- LLM error: `{_cell(audit.llm_error)}`")
    if audit.retrieved:
        lines.extend(["", "Retrieved knowledge for this project:", ""])
        for doc in audit.retrieved:
            lines.append(f"- `{doc.kind}` **{doc.doc_id}** (score {doc.score:.3f}) — {_cell(doc.title)}")
    if audit.diagnostics:
        lines.extend(["", "## Diagnostics", ""])
        lines.extend(f"- {_cell(item)}" for item in audit.diagnostics)
    lines.extend([
        "",
        "## Honest boundary",
        "",
        "SELF autonomous is a trained, project-aware triage agent. It reads the",
        "whole repository, matches it against real incident playbooks, and",
        "assembles exploit paths. It does not execute EVM/BPF, does not prove",
        "invariants, and can still false-positive or false-negative.",
        "",
    ])
    return "\n".join(lines)


def _finding_block(item) -> list:
    return [
        f"### {item.severity} — {item.title}",
        "",
        f"- **ID:** `{item.id}`",
        f"- **Source:** {item.source} / `{item.playbook_id or '-'}`",
        f"- **Location:** `{item.file}:{item.line}` ({item.language})",
        f"- **Confidence:** {item.confidence}",
        "",
        item.description,
        "",
        "**Exploit scenario**",
        "",
        item.exploit_scenario,
        "",
        "**Remediation**",
        "",
        item.remediation,
        "",
        f"**Proof obligation:** {item.proof_obligation}",
        "",
        f"**Regression:** `{_cell(item.regression_recipe)}`",
        "",
        "```",
        item.snippet or "(no snippet)",
        "```",
        "",
    ]


def _counts(severities) -> dict:
    counts = {}
    for sev in severities:
        counts[sev] = counts.get(sev, 0) + 1
    return counts


def _cell(value: Optional[str]) -> str:
    return (value or "").replace("|", "\\|").replace("\n", " ")
